// Every audit / activity action code the API can write. The admin audit log filter and the activity timelines use these;
// each code has a translation under 'auditAction.<CODE>' (i18n/p2/core.*.ts) and each entity under 'auditEntity.<entity>'.
export const AUDIT_ACTIONS = [
  'USER_LOGIN', 'USER_CREATED', 'USER_UPDATED', 'USER_ASSIGNMENTS_UPDATED', 'USER_PERMISSIONS_CHANGED', 'PASSWORD_CHANGED', 'BRANDING_UPDATED',
  'CLIENT_CREATED', 'CLIENT_UPDATED', 'CLIENT_ARCHIVED', 'CLIENT_STATUS_CHANGED',
  'CONTACT_CREATED', 'CONTACT_UPDATED', 'CONTACT_DELETED',
  'INTERNAL_NOTE_CREATED', 'INTERNAL_NOTE_UPDATED', 'INTERNAL_NOTE_DELETED',
  'ONBOARDING_STARTED', 'ONBOARDING_ITEM_ADDED', 'ONBOARDING_ITEM_UPDATED', 'ONBOARDING_ITEM_DELETED',
  'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_STATUS_CHANGED', 'PROJECT_DELETED', 'MILESTONE_CREATED', 'MILESTONE_UPDATED', 'MILESTONE_DELETED',
  'TASK_CREATED', 'TASK_UPDATED', 'TASK_ASSIGNED', 'TASK_STATUS_CHANGED', 'TASK_COMPLETED', 'TASK_DELETED',
  'CAMPAIGN_CREATED', 'CAMPAIGN_UPDATED', 'CAMPAIGN_DELETED',
  'CONTENT_CREATED', 'CONTENT_UPDATED', 'CONTENT_STATUS_CHANGED', 'CONTENT_SENT_FOR_APPROVAL', 'CONTENT_DELETED',
  'DELIVERABLE_CREATED', 'DELIVERABLE_UPDATED', 'DELIVERABLE_SUBMITTED', 'DELIVERABLE_APPROVED', 'CHANGES_REQUESTED', 'DELIVERABLE_NEW_VERSION', 'DELIVERABLE_PUBLISHED',
  'PROOFING_COMMENT_CREATED', 'PROOFING_COMMENT_RESOLVED',
  'REQUEST_CREATED', 'REQUEST_UPDATED', 'REQUEST_STATUS_CHANGED', 'COMMENT_CREATED',
  'REPORT_CREATED', 'REPORT_DELETED', 'REPORT_EXPORTED',
  'FILE_UPLOADED', 'FILE_DELETED',
  'CONTRACT_CREATED', 'CONTRACT_UPDATED', 'CONTRACT_STATUS_CHANGED', 'CONTRACT_DELETED',
  'INVOICE_CREATED', 'INVOICE_UPDATED', 'INVOICE_STATUS_CHANGED', 'INVOICE_DELETED',
  // phase 3: tasks
  'TASK_PRIORITY_CHANGED', 'TASK_DUE_DATE_CHANGED', 'TASK_ARCHIVED', 'TASK_UNARCHIVED', 'TASK_BULK_UPDATED', 'SUBTASK_CREATED', 'SUBTASK_COMPLETED',
  'TASK_DEPENDENCY_ADDED', 'TASK_DEPENDENCY_REMOVED', 'TASK_RECURRENCE_SET', 'TASK_RECURRENCE_REMOVED', 'TASK_AUTOMATION_RAN', 'TASK_TEMPLATE_APPLIED',
  'COMMENT_UPDATED', 'COMMENT_DELETED', 'SPACE_CREATED', 'SPACE_UPDATED', 'SPACE_DELETED', 'SPACE_STATUSES_UPDATED', 'FOLDER_CREATED', 'FOLDER_UPDATED',
  'FOLDER_DELETED', 'LIST_CREATED', 'LIST_UPDATED', 'LIST_DELETED', 'CUSTOM_FIELD_CREATED', 'CUSTOM_FIELD_UPDATED', 'CUSTOM_FIELD_DELETED', 'TAG_UPDATED',
  'TAG_DELETED', 'TASK_TEMPLATE_CREATED', 'TASK_TEMPLATE_UPDATED', 'TASK_TEMPLATE_DELETED', 'AUTOMATION_CREATED', 'AUTOMATION_UPDATED', 'AUTOMATION_DELETED',
  // phase 3: attendance
  'ATTENDANCE_CHECK_IN', 'ATTENDANCE_CHECK_OUT', 'ATTENDANCE_BREAK_STARTED', 'ATTENDANCE_BREAK_ENDED', 'ATTENDANCE_CREATED', 'ATTENDANCE_CORRECTED',
  'ATTENDANCE_MEMBER_UPDATED', 'LEAVE_REQUESTED', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'LEAVE_CANCELLED', 'WORK_SCHEDULE_CREATED', 'WORK_SCHEDULE_UPDATED',
  'WORK_SCHEDULE_DELETED', 'HOLIDAY_CREATED', 'HOLIDAY_DELETED',
] as const;

export const AUDIT_ENTITIES = [
  'user', 'client', 'contact', 'internal_note', 'onboarding_item', 'project', 'milestone', 'task', 'campaign', 'content', 'deliverable', 'proofing',
  'request', 'report', 'file', 'contract', 'invoice', 'settings',
  'space', 'folder', 'list', 'custom_field', 'tag', 'task_template', 'automation', 'attendance', 'leave', 'work_schedule', 'holiday',
] as const;
