import fs from 'node:fs';
import path from 'node:path';
import type { StorageProvider } from './StorageProvider';
import { Errors } from '../lib/errors';

// Keys are generated by us: <uuid>.<ext>. Anything else is rejected (path traversal defence).
const KEY_RE = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(\.[a-z0-9]{1,5})?$/;

export class LocalStorage implements StorageProvider {
  private readonly base: string;

  constructor(baseDir: string) {
    this.base = path.resolve(baseDir);
    fs.mkdirSync(this.base, { recursive: true });
  }

  /** Maps a key to an absolute path and guarantees it stays inside the upload directory. */
  private resolve(key: string): string {
    if (!KEY_RE.test(key)) throw Errors.notFound();
    const full = path.resolve(this.base, key);
    if (!full.startsWith(this.base + path.sep)) throw Errors.notFound();
    return full;
  }

  async put(key: string, data: Buffer): Promise<void> {
    // 'wx' = never overwrite an existing file
    await fs.promises.writeFile(this.resolve(key), data, { flag: 'wx', mode: 0o640 });
  }

  async get(key: string) {
    const full = this.resolve(key);
    try {
      const stat = await fs.promises.stat(full);
      return { stream: fs.createReadStream(full), size: stat.size };
    } catch {
      throw Errors.notFound();
    }
  }

  async delete(key: string): Promise<void> {
    await fs.promises.rm(this.resolve(key), { force: true });
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fs.promises.access(this.resolve(key));
      return true;
    } catch {
      return false;
    }
  }
}
