import type { Readable } from 'node:stream';
import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
  HeadObjectCommand,
} from '@aws-sdk/client-s3';
import type { StorageProvider } from './StorageProvider';
import { Errors } from '../lib/errors';

// Keys are generated by us: <uuid>.<ext>. Anything else is rejected (defence in depth - the
// same rule LocalStorage enforces, kept here too since both implement the same interface).
const KEY_RE = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(\.[a-z0-9]{1,5})?$/;

export interface S3StorageOptions {
  bucket: string;
  endpoint: string;
  region: string;
  accessKeyId: string;
  secretAccessKey: string;
  forcePathStyle?: boolean;
}

/**
 * S3-compatible object storage (Cloudflare R2, AWS S3, MinIO, Backblaze B2, ...).
 * The database only ever stores the opaque `key` this provider was given - nothing else in the
 * app needs to change to move between LocalStorage and this.
 */
export class S3Storage implements StorageProvider {
  private readonly client: S3Client;
  private readonly bucket: string;

  constructor(opts: S3StorageOptions) {
    if (!opts.bucket || !opts.endpoint || !opts.accessKeyId || !opts.secretAccessKey) {
      throw new Error(
        'S3Storage requires S3_BUCKET, S3_ENDPOINT, S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY to be set.',
      );
    }
    this.bucket = opts.bucket;
    this.client = new S3Client({
      region: opts.region || 'auto',
      endpoint: opts.endpoint,
      // R2 and most S3-compatible hosts serve buckets as a path segment, not a subdomain.
      forcePathStyle: opts.forcePathStyle ?? true,
      credentials: { accessKeyId: opts.accessKeyId, secretAccessKey: opts.secretAccessKey },
    });
  }

  private assertKey(key: string): string {
    if (!KEY_RE.test(key)) throw Errors.notFound();
    return key;
  }

  async put(key: string, data: Buffer, opts: { contentType: string }): Promise<void> {
    this.assertKey(key);
    // 'wx'-equivalent: LocalStorage never overwrites an existing key, and callers always hand
    // out a fresh UUID key per upload. S3 has no atomic create-if-absent, so this check-then-put
    // is a good-enough match for how the app actually calls this, not a hard guarantee under a
    // concurrent write of the exact same key (which never happens in practice - keys are never
    // reused).
    if (await this.exists(key)) throw new Error(`Storage key already exists: ${key}`);
    await this.client.send(
      new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: data, ContentType: opts.contentType }),
    );
  }

  async get(key: string): Promise<{ stream: Readable; size: number }> {
    this.assertKey(key);
    try {
      const res = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: key }));
      if (!res.Body) throw Errors.notFound();
      return { stream: res.Body as Readable, size: res.ContentLength ?? 0 };
    } catch (err) {
      if ((err as { name?: string }).name === 'NoSuchKey') throw Errors.notFound();
      throw err;
    }
  }

  async delete(key: string): Promise<void> {
    this.assertKey(key);
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }

  async exists(key: string): Promise<boolean> {
    this.assertKey(key);
    try {
      await this.client.send(new HeadObjectCommand({ Bucket: this.bucket, Key: key }));
      return true;
    } catch {
      return false;
    }
  }
}
