import { useState } from 'react';
import { CONTRACT_STATUSES } from '@shared/enums';
import { api } from '@/api/client';
import { useAction } from '@/api/hooks';
import type { ContractRow } from '@/api/types.finance';
import { useI18n } from '@/i18n';
import { fieldErrors, fieldText } from '@/i18n/errors';
import { Button } from '@/components/ui/Button';
import { Checkbox, Field, Input, Select, Textarea } from '@/components/ui/Form';
import { Modal } from '@/components/ui/Modal';
import { useClientOptions } from '@/components/shared/options';
import { dayStr } from './FinanceShared';

/** Create / edit a contract. The contract number is generated by the server. */
export function ContractFormModal({ open, onClose, contract, defaultClientId, onSaved }: {
  open: boolean; onClose: () => void; contract?: ContractRow; defaultClientId?: string; onSaved?: (c: ContractRow) => void;
}) {
  const { t, label } = useI18n();
  const editing = !!contract;
  const { clients } = useClientOptions(open);
  const [f, setF] = useState(() => ({
    clientId: contract?.clientId ?? defaultClientId ?? '', name: contract?.name ?? '', status: contract?.status ?? 'DRAFT',
    startDate: dayStr(contract?.startDate), endDate: dayStr(contract?.endDate), renewalDate: dayStr(contract?.renewalDate),
    value: contract ? String(contract.value) : '', notes: contract?.notes ?? '', visibleToClient: contract?.visibleToClient ?? false,
  }));
  const set = <K extends keyof typeof f>(k: K, v: (typeof f)[K]) => setF((s) => ({ ...s, [k]: v }));

  const save = useAction(
    async () => {
      const body = {
        name: f.name.trim(), status: f.status, startDate: f.startDate || null, endDate: f.endDate || null, renewalDate: f.renewalDate || null,
        value: Number(f.value || 0), notes: f.notes.trim() || null, visibleToClient: f.visibleToClient,
      };
      const res = editing ? await api.patch<{ item: ContractRow }>(`/contracts/${contract!.id}`, body) : await api.post<{ item: ContractRow }>('/contracts', { ...body, clientId: f.clientId });
      return res.item;
    },
    { success: editing ? t('finance.contractUpdated') : t('finance.contractCreated'), onSuccess: (item) => { onClose(); onSaved?.(item); } },
  );
  const errs = fieldErrors(save.error);
  const err = (k: string) => fieldText(t, errs[k]);

  return (
    <Modal
      open={open} onClose={onClose} size="lg"
      title={editing ? t('finance.editContract') : t('finance.newContract')}
      description={editing ? contract!.contractNumber : t('finance.numberAuto')}
      footer={<><Button variant="secondary" onClick={onClose} className="max-sm:h-11">{t('common.cancel')}</Button><Button variant="brand" onClick={() => save.mutate(undefined)} loading={save.isPending} disabled={!f.name.trim() || (!editing && !f.clientId)} className="max-sm:h-11">{editing ? t('common.saveChanges') : t('finance.createContract')}</Button></>}
    >
      <form onSubmit={(e) => { e.preventDefault(); save.mutate(undefined); }} className="grid gap-4 sm:grid-cols-2">
        <Field label={t('finance.contractName')} error={err('name')} required className="sm:col-span-2">{(id) => <Input id={id} value={f.name} maxLength={160} onChange={(e) => set('name', e.target.value)} invalid={!!errs.name} />}</Field>
        <Field label={t('common.client')} error={err('clientId')} required>
          {(id) => (
            <Select id={id} value={f.clientId} onChange={(e) => set('clientId', e.target.value)} disabled={editing} invalid={!!errs.clientId}>
              <option value="">{t('common.select')}</option>
              {clients.map((c) => <option key={c.id} value={c.id}>{c.companyName}</option>)}
            </Select>
          )}
        </Field>
        <Field label={t('common.status')} error={err('status')}>{(id) => <Select id={id} value={f.status} onChange={(e) => set('status', e.target.value as ContractRow['status'])}>{CONTRACT_STATUSES.map((s) => <option key={s} value={s}>{label('contractStatus', s)}</option>)}</Select>}</Field>
        <Field label={t('finance.startDate')} error={err('startDate')}>{(id) => <Input id={id} type="date" value={f.startDate} onChange={(e) => set('startDate', e.target.value)} />}</Field>
        <Field label={t('finance.endDate')} error={err('endDate')}>{(id) => <Input id={id} type="date" value={f.endDate} onChange={(e) => set('endDate', e.target.value)} invalid={!!errs.endDate} />}</Field>
        <Field label={t('finance.renewalDate')} hint={t('common.optional')} error={err('renewalDate')}>{(id) => <Input id={id} type="date" value={f.renewalDate} onChange={(e) => set('renewalDate', e.target.value)} />}</Field>
        <Field label={t('finance.contractValue')} error={err('value')}>{(id) => <Input id={id} type="number" inputMode="decimal" min="0" step="0.01" value={f.value} onChange={(e) => set('value', e.target.value)} invalid={!!errs.value} />}</Field>
        <Field label={t('finance.internalNotes')} hint={t('common.internalOnly')} error={err('notes')} className="sm:col-span-2">{(id) => <Textarea id={id} value={f.notes} maxLength={4000} onChange={(e) => set('notes', e.target.value)} />}</Field>
        <div className="rounded-xl border border-line bg-zinc-50 p-4 sm:col-span-2">
          <Checkbox checked={f.visibleToClient} onChange={(e) => set('visibleToClient', e.target.checked)} label={<span className="font-medium">{t('finance.shareWithClient')}</span>} />
          <p className="mt-1.5 ps-6 text-xs leading-relaxed text-zinc-500">{t('finance.shareExplain')}</p>
        </div>
        <button type="submit" className="hidden" />
      </form>
    </Modal>
  );
}
